# https://golangci-lint.run/usage/configuration#config-file

linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell

run:
  deadline: 4m
  skip-dirs:
    - ".*/go/pkg/mod/golang\\.org/toolchain@.*"
    - ".*/go/pkg/mod/golang\\.org/x/.*"
    - "/usr/local/go/.*"