kubernetes:
    clusters:
        - name: "cluster1"
          kubeconfigpath: "/Users/wpy/.kube/config"
          ymlpath: ""
prometheus:
    servers:
        - name: "prometheus"
          address: "http://localhost:9092"
          auth: ""
log:
    clusters:
        - name: ""
          collection:
            enable: true
            local: ""
          analysis:
            enable: true
            local: ""
          display:
            displayType: ""
            path: ""
            local: ""
context:
    kubernetes: "cluster1"
    prometheus: "prometheus"
    log: ""
